s = "45.8"
a = "63.9"
first_name = "folorunso"
last_name = "michael"
name = "Michael"
age = 20
pi = 3.14
Numbers = [1, 2, 3, 4]
print(type(name))
print(type(age))
print(type(pi))
print(type(Numbers))
<class 'str'>
<class 'int'>
<class 'float'>
<class 'list'>
name = "john"
full_name = "j james"
pi = 4.17
print(name)
print(full_name)
print(pi)
house = "Bernhard_Bastlein_Straße"
houseNumber = 04.8
pi = 3.14
brand = "Apple"
age = 8
number = []
pi = 5.18
isYouth = False
isYouth = True
print(type(isYouth))
print(type(brand))
print(type(age))
print(type(number))
print(type(pi))
print(type(isYouth))
<class 'str'>
<class 'int'>
<class 'list'>
<class 'float'>
<class 'bool'>
def hello():
    return "hello"
brand: str = "Amigoscode"
isAdult: bool = True
print(type(hello))
print(type(brand))
print(type(isAdult))
<class 'function'>
<class 'str'>
<class 'bool'>